# Generated by Django 3.2.3 on 2021-05-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bewertung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bw1', models.IntegerField()),
                ('bw2', models.IntegerField()),
                ('bw3', models.IntegerField()),
                ('anm', models.TextField()),
                ('test', models.TextField()),
            ],
        ),
    ]
