# Generated by Django 3.2.3 on 2021-05-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioa', '0002_remove_bewertung_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('videofile', models.FileField(upload_to='videos')),
            ],
        ),
    ]
