# Generated by Django 3.2.3 on 2021-05-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioa', '0003_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='previewimg',
            field=models.FileField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
