# Generated by Django 3.2.4 on 2021-06-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioa', '0005_bewertungneu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bewertungneu',
        ),
    ]
